version: '3.5'

services:
  db:
    container_name: fitly_db
    image: postgres:11
    environment:
      POSTGRES_DB: fitly
      POSTGRES_USER: fitly
      POSTGRES_PASSWORD: fitly
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - fitly
    restart: unless-stopped

  pgadmin:
    container_name: fitly_pgadmin
    image: dpage/pgadmin4:4.6
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@postgres.org
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    networks:
      - fitly
    restart: unless-stopped
    
  server:
    container_name: fitly_server
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    restart: unless-stopped
    env_file:
        - .env.dev
    volumes:
        - ./:/code
    ports:
        - "5000:5000"
    networks:
        - fitly

  front:
    container_name: fitly_front
    build:
      context: .
      dockerfile: ./front/Dockerfile
    restart: unless-stopped
    env_file:
        - .env.dev
    command: bash -c "npx vue-cli-service serve"
    volumes:
        - ./:/code
    ports:
        - "8080:8080"
    networks:
        - fitly



networks:
  fitly:
    driver: bridge

volumes:
    pgadmin:
    postgres:
