version: '3.5'

services:
  db:
    container_name: fitly_db
    image: postgres:11
    environment:
      POSTGRES_DB: fitly
      POSTGRES_USER: fitly
      POSTGRES_PASSWORD: fitly
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - fitly
    restart: unless-stopped
    
  server:
    container_name: fitly_server
    build: 
      context: .
      dockerfile: ./server/Dockerfile
    restart: unless-stopped
    env_file:
        - .env.prod
    volumes:
        - ./:/code
    ports:
        - "5000:5000"
    networks:
        - fitly

  front:
    container_name: fitly_front
    build:
      context: .
      dockerfile: ./front/Dockerfile
      #    restart: unless-stopped
    env_file:
        - .env.prod
    command: bash -c "npx vue-cli-service build"
    volumes:
        - ./:/code
    ports:
        - "8080:8080"
    networks:
        - fitly



networks:
  fitly:
    driver: bridge

volumes:
    postgres:
